
spring:
  datasource:
    url: jdbc:derby:/home/ssenko/reportdb;create=true
    username: dbuser
    password: dbpass
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
  jpa:
    database-platform: org.hibernate.dialect.DerbyDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
#  mvc:
#    static-path-pattern: /ui/**

# Server configuration
server:
 port: 8080


logging:
  level:
    org.springframework.web: ERROR
    ua.pp.ssenko: DEBUG
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'
    file: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'
  file: /logs/application.log

oauth2:
  client-id: 818317884453-804qunbaqtgop3v3d8b6nonlnq057vvr.apps.googleusercontent.com
  client-secret: 6sbNK_t0A3g0_5ouFlpJJQm5
  user-authorization-uri: https://accounts.google.com/o/oauth2/auth
  scopes: https://www.googleapis.com/auth/userinfo.email
  redirect-uri: http://localhost:8080/api/oauth2callback
  redirect-path: /api/oauth2callback
  access-token-uri: https://accounts.google.com/o/oauth2/token
